/*
 * Anim Core mod
 *  Copyright (C)  2026  LeisureTimeDock
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package top.leisuretimedock.animationcore;


import net.minecraftforge.event.AddReloadListenerEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import top.leisuretimedock.animationcore.animation.AnimationDataManager;
import top.leisuretimedock.animationcore.animation.LayerDataManager;


@Mod(AnimationCore.MOD_ID)
public class AnimationCore {
    public static final Logger LOGGER = LoggerFactory.getLogger(AnimationCore.class);
    public static final String MOD_ID = "animcore";

    public AnimationCore() {
       LOGGER.info("Loading Animation Core");
    }
    @Mod.EventBusSubscriber(modid = MOD_ID, bus = Mod.EventBusSubscriber.Bus.FORGE)
   public static class CommonGame {
       @SubscribeEvent
       public static void onAddReloadListeners(AddReloadListenerEvent event) {
           event.addListener(AnimationDataManager.INSTANCE);
           event.addListener(LayerDataManager.INSTANCE);
       }
   }
}
